Update cd-hit and mmseq installation17

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,23 +62,18 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y cd-hit mmseqs2
 
-    - name: Install cd-hit (Windows)
-      if: runner.os == 'Windows'
-      shell: pwsh
+    - name: Set up WSL and compile cd-hit
+      shell: bash
       run: |
-        curl -L -o cd-hit.tar.gz https://github.com/weizhongli/cdhit/releases/download/V4.8.1/cd-hit-v4.8.1-2019-0228.tar.gz
-        $cdhitDir = "$Env:USERPROFILE\cdhit"
-        New-Item -ItemType Directory -Force -Path $cdhitDir
-        tar -xzf cd-hit.tar.gz -C $cdhitDir
-        $cdhitBinPath = "$cdhitDir\cd-hit-v4.8.1-2019-0228\bin"
-        Write-Host "cd-hit binary path: $cdhitBinPath"
-        echo "$cdhitBinPath" | Out-File -Append -FilePath $Env:GITHUB_PATH
-        [Environment]::SetEnvironmentVariable("PATH", "$Env:PATH;$cdhitBinPath", "Process")
-        Write-Host "Contents of cd-hit bin directory:"
-        Get-ChildItem $cdhitBinPath
+        sudo apt update
+        sudo apt install -y build-essential zlib1g-dev
+        wget https://github.com/weizhongli/cdhit/releases/download/V4.8.1/cd-hit-v4.8.1-2019-0228.tar.gz
+        tar -xzf cd-hit-v4.8.1-2019-0228.tar.gz
+        cd cd-hit-v4.8.1-2019-0228
+        make
+        sudo cp cd-hit /usr/local/bin/
 
     - name: Install mmseqs2 (Windows)
-      if: runner.os == 'Windows'
       shell: pwsh
       run: |
         curl -L -o mmseqs2.zip https://mmseqs.com/latest/mmseqs-win64.zip
@@ -92,23 +87,17 @@ jobs:
         Write-Host "Contents of mmseqs2 directory:"
         Get-ChildItem $mmseqsBinPath
 
-    - name: Verify cd-hit installation
-      if: runner.os == 'Windows'
-      shell: pwsh
+    - name: Verify cd-hit installation (WSL)
+      shell: bash
       run: |
-        $cdhitBinPath = "$Env:USERPROFILE\cdhit\cd-hit-v4.8.1-2019-0228\bin"
-        $env:Path += ";$cdhitBinPath"
-        Write-Host "Updated PATH: $env:Path"
-        Write-Host "Checking cd-hit binary in PATH:"
-        if (-Not (Get-Command cd-hit -ErrorAction SilentlyContinue)) {
-          Write-Error "cd-hit not found in PATH"
-        } else {
-          Write-Host "cd-hit found in PATH"
-          cd-hit --version
-        }
+        if ! command -v cd-hit &> /dev/null
+        then
+            echo "cd-hit could not be found"
+            exit 1
+        fi
+        cd-hit --version
 
     - name: Verify mmseqs2 installation
-      if: runner.os == 'Windows'
       shell: pwsh
       run: |
         $mmseqsBinPath = "$Env:USERPROFILE\mmseqs\mmseqs-win64"
@@ -121,6 +110,7 @@ jobs:
           Write-Host "mmseqs found in PATH"
           mmseqs --version
         }
+
 
     - name: Run Tests
       run: pytest tests
